"""ChaosCase — adversarial test case generated by ChaosCreator."""

from __future__ import annotations

from enum import StrEnum
from uuid import uuid4

from pydantic import BaseModel, Field


class AttackStrategy(StrEnum):
    DIRECT = "direct_violation"
    EDGE_CASE = "edge_case"
    SUBTLE_HARM = "subtle_harm"
    JAILBREAK = "jailbreak_roleplay"
    MULTILINGUAL = "multilingual_evasion"
    CONTEXT_INJECTION = "context_injection"
    GRADUAL_ESCALATION = "gradual_escalation"
    EMOTIONAL_MANIPULATION = "emotional_manipulation"


class Difficulty(StrEnum):
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"
    EXTREME = "extreme"


class ExpectedAction(StrEnum):
    PASS = "PASS"
    FLAG = "FLAG"
    BLOCK = "BLOCK"


class ChaosCase(BaseModel):
    """A boundary-testing case produced by the ChaosCreator agent."""

    case_id: str = Field(default_factory=lambda: str(uuid4()))
    request_item_id: str | None = Field(
        default=None,
        description="Local generation request ID; required for new generation, optional for history",
    )
    content: str = Field(..., min_length=1, description="The generated adversarial content")
    attack_strategy: AttackStrategy = Field(..., description="Attack strategy used")
    target_dimension: str = Field(..., min_length=1, description="Policy dimension being targeted")
    difficulty: Difficulty = Field(default=Difficulty.MEDIUM)
    expected_action: ExpectedAction = Field(
        ..., description="Legacy generation hint; not a verified label or ground truth"
    )
    reasoning: str = Field(..., min_length=1, description="ChaosCreator's intent explanation")
    metadata: dict = Field(default_factory=dict)
