"""HTML 可视化质量报告生成器。

生成包含以下内容的自包含 HTML 报告（无外部依赖）：
- 数据集概览 KPI 卡片
- 质量分数分布直方图（内联 SVG）
- 策略覆盖率表格
- IAA 指标展示
- 飞轮迭代质量趋势（如有）
- 攻击策略分布

参考：Garak HTML Report 风格
"""

from __future__ import annotations

import html as html_mod
from datetime import UTC, datetime
from pathlib import Path


def _esc(text: str) -> str:
    """HTML 转义，防止 XSS 注入。"""
    return html_mod.escape(str(text))


def generate_html_report(
    *,
    dataset_name: str = "EcoAlign-Forge DPO Dataset",
    total_pairs: int = 0,
    avg_quality: float = 0.0,
    avg_preference_gap: float = 0.0,
    interception_rate: float = 0.0,
    decision_counts: dict[str, int] | None = None,
    dimension_stats: dict[str, dict] | None = None,
    rule_coverage: dict[str, int] | None = None,
    iaa_metrics: dict | None = None,
    flywheel_summary: dict | None = None,
    quality_distribution: list[float] | None = None,
    output_path: str | Path = "./data/report.html",
) -> Path:
    """生成自包含 HTML 质量报告。"""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    decision_counts = decision_counts or {}
    dimension_stats = dimension_stats or {}
    rule_coverage = rule_coverage or {}
    quality_distribution = quality_distribution or []
    timestamp = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M UTC")

    # KPI 卡片
    kpi_cards = _render_kpi_cards(
        total_pairs, avg_quality, avg_preference_gap, interception_rate
    )

    # 决策分布表
    decision_table = _render_decision_table(decision_counts)

    # 维度统计表
    dimension_table = _render_dimension_table(dimension_stats)

    # 规则覆盖率表
    rule_table = _render_rule_coverage(rule_coverage)

    # IAA 指标
    iaa_section = _render_iaa_section(iaa_metrics) if iaa_metrics else ""

    # 飞轮趋势
    flywheel_section = (
        _render_flywheel_section(flywheel_summary)
        if flywheel_summary
        else ""
    )

    # 质量分布 SVG 直方图
    quality_chart = _render_quality_histogram(quality_distribution)

    html = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{_esc(dataset_name)} — 质量报告</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f7fa; color: #1f2329; line-height: 1.6; padding: 24px; }}
.container {{ max-width: 1100px; margin: 0 auto; }}
h1 {{ font-size: 28px; margin-bottom: 8px; }}
.subtitle {{ color: #646a73; font-size: 14px; margin-bottom: 32px; }}
.kpi-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; margin-bottom: 32px; }}
.kpi-card {{ background: #fff; border-radius: 12px; padding: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }}
.kpi-value {{ font-size: 32px; font-weight: 700; color: #5178c6; }}
.kpi-label {{ font-size: 13px; color: #646a73; margin-top: 4px; }}
.section {{ background: #fff; border-radius: 12px; padding: 24px; margin-bottom: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }}
.section h2 {{ font-size: 18px; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 2px solid #f0f4fc; }}
table {{ width: 100%; border-collapse: collapse; font-size: 14px; }}
th {{ background: #f0f4fc; text-align: left; padding: 10px 12px; font-weight: 600; }}
td {{ padding: 10px 12px; border-bottom: 1px solid #f0f0f0; }}
tr:hover td {{ background: #fafbfc; }}
.badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }}
.badge-green {{ background: #dff5e5; color: #509863; }}
.badge-yellow {{ background: #fef1ce; color: #d4b45b; }}
.badge-red {{ background: #fee3e2; color: #d25d5a; }}
.badge-blue {{ background: #f0f4fc; color: #5178c6; }}
.progress-bar {{ width: 100%; height: 8px; background: #f0f0f0; border-radius: 4px; overflow: hidden; }}
.progress-fill {{ height: 100%; border-radius: 4px; transition: width 0.3s; }}
.chart-container {{ text-align: center; padding: 16px 0; }}
.footer {{ text-align: center; color: #999; font-size: 12px; margin-top: 32px; }}
</style>
</head>
<body>
<div class="container">
<h1>{_esc(dataset_name)}</h1>
<p class="subtitle">数据质量报告 · 生成时间 {_esc(timestamp)} · by EcoAlign-Forge</p>

{kpi_cards}

<div class="section">
<h2>决策分布</h2>
{decision_table}
</div>

{quality_chart}

<div class="section">
<h2>维度拦截率</h2>
{dimension_table}
</div>

<div class="section">
<h2>规则覆盖率</h2>
{rule_table}
</div>

{iaa_section}
{flywheel_section}

<p class="footer">Generated by EcoAlign-Forge · Multi-Agent DPO Data Synthesis Factory</p>
</div>
</body>
</html>"""

    path.write_text(html, encoding="utf-8")
    return path


def _render_kpi_cards(
    total: int, quality: float, gap: float, intercept: float
) -> str:
    return f"""<div class="kpi-grid">
<div class="kpi-card"><div class="kpi-value">{total}</div><div class="kpi-label">DPO 偏好对总数</div></div>
<div class="kpi-card"><div class="kpi-value">{quality:.2f}</div><div class="kpi-label">平均质量分</div></div>
<div class="kpi-card"><div class="kpi-value">{gap:.2f}</div><div class="kpi-label">平均偏好差距</div></div>
<div class="kpi-card"><div class="kpi-value">{intercept:.1%}</div><div class="kpi-label">拦截率 (T0+T1)</div></div>
</div>"""


def _render_decision_table(counts: dict[str, int]) -> str:
    total = sum(counts.values()) or 1
    rows = ""
    colors = {
        "T0_Block": "red", "T1_Shadowban": "yellow",
        "T2_Normal": "blue", "T3_Recommend": "green",
    }
    for dec in ("T0_Block", "T1_Shadowban", "T2_Normal", "T3_Recommend"):
        n = counts.get(dec, 0)
        pct = n / total * 100
        color = colors.get(dec, "blue")
        rows += f"""<tr>
<td><span class="badge badge-{color}">{_esc(dec)}</span></td>
<td>{n}</td>
<td>{pct:.1f}%</td>
<td><div class="progress-bar"><div class="progress-fill" style="width:{pct}%;background:{'#d25d5a' if color == 'red' else '#d4b45b' if color == 'yellow' else '#5178c6' if color == 'blue' else '#509863'}"></div></div></td>
</tr>"""
    return f"<table><tr><th>档位</th><th>数量</th><th>占比</th><th>分布</th></tr>{rows}</table>"


def _render_dimension_table(stats: dict[str, dict]) -> str:
    if not stats:
        return "<p>暂无维度数据</p>"
    rows = ""
    for dim, s in stats.items():
        rate = s.get("interception_rate", 0)
        color = "red" if rate > 0.6 else "yellow" if rate > 0.3 else "green"
        rows += f"""<tr>
<td>{_esc(dim)}</td>
<td>{s.get('total', 0)}</td>
<td>{s.get('intercepted', 0)}</td>
<td><span class="badge badge-{color}">{rate:.1%}</span></td>
</tr>"""
    return f"<table><tr><th>维度</th><th>总数</th><th>拦截数</th><th>拦截率</th></tr>{rows}</table>"


def _render_rule_coverage(coverage: dict[str, int]) -> str:
    if not coverage:
        return "<p>暂无规则覆盖数据</p>"
    rows = ""
    for rule_id in sorted(coverage.keys()):
        hits = coverage[rule_id]
        color = "green" if hits > 0 else "red"
        rows += f'<tr><td>{_esc(rule_id)}</td><td>{hits}</td><td><span class="badge badge-{color}">{"已覆盖" if hits > 0 else "未覆盖"}</span></td></tr>'
    covered = sum(1 for h in coverage.values() if h > 0)
    total = len(coverage)
    rate = covered / total if total > 0 else 0
    return f"""<p>覆盖率: <strong>{covered}/{total} ({rate:.0%})</strong></p>
<table><tr><th>规则编号</th><th>命中次数</th><th>状态</th></tr>{rows}</table>"""


def _render_iaa_section(metrics: dict) -> str:
    kappa = metrics.get("avg_cohens_kappa", 0)
    alpha = metrics.get("krippendorffs_alpha", 0)
    low_conf = metrics.get("low_confidence", False)

    kappa_color = "green" if kappa > 0.6 else "yellow" if kappa > 0.4 else "red"
    alpha_color = "green" if alpha > 0.667 else "yellow" if alpha > 0.4 else "red"

    return f"""<div class="section">
<h2>标注者一致性 (IAA)</h2>
<div class="kpi-grid">
<div class="kpi-card"><div class="kpi-value" style="color:{'#509863' if kappa_color == 'green' else '#d4b45b' if kappa_color == 'yellow' else '#d25d5a'}">{kappa:.3f}</div><div class="kpi-label">Cohen's Kappa (平均)</div></div>
<div class="kpi-card"><div class="kpi-value" style="color:{'#509863' if alpha_color == 'green' else '#d4b45b' if alpha_color == 'yellow' else '#d25d5a'}">{alpha:.3f}</div><div class="kpi-label">Krippendorff's Alpha</div></div>
<div class="kpi-card"><div class="kpi-value">{'⚠️ 低' if low_conf else '✅ 高'}</div><div class="kpi-label">置信度</div></div>
</div>
</div>"""


def _render_flywheel_section(summary: dict) -> str:
    trend = summary.get("quality_trend", [])
    improvement = summary.get("total_improvement", "0%")
    total_rounds = summary.get("total_rounds", 0)
    total_pairs = summary.get("cumulative_dpo_pairs", 0)

    # SVG 趋势图
    chart = ""
    if len(trend) > 1:
        w, h = 500, 150
        max_val = max(trend) or 1
        points = []
        for i, v in enumerate(trend):
            x = 40 + i * (w - 60) / (len(trend) - 1)
            y = h - 20 - (v / max_val) * (h - 40)
            points.append(f"{x},{y}")
        polyline = " ".join(points)
        dots = "".join(
            f'<circle cx="{p.split(",")[0]}" cy="{p.split(",")[1]}" r="4" fill="#5178c6"/>'
            for p in points
        )
        chart = f"""<div class="chart-container">
<svg width="{w}" height="{h}" viewBox="0 0 {w} {h}">
<polyline points="{polyline}" fill="none" stroke="#5178c6" stroke-width="2"/>
{dots}
<text x="20" y="{h - 5}" font-size="11" fill="#999">Round 1</text>
<text x="{w - 60}" y="{h - 5}" font-size="11" fill="#999">Round {len(trend)}</text>
</svg>
<p style="color:#646a73;font-size:13px">质量趋势（每轮平均质量分）</p>
</div>"""

    return f"""<div class="section">
<h2>数据飞轮迭代</h2>
<div class="kpi-grid">
<div class="kpi-card"><div class="kpi-value">{total_rounds}</div><div class="kpi-label">迭代轮次</div></div>
<div class="kpi-card"><div class="kpi-value">{total_pairs}</div><div class="kpi-label">累计 DPO 对</div></div>
<div class="kpi-card"><div class="kpi-value">{improvement}</div><div class="kpi-label">质量提升</div></div>
</div>
{chart}
</div>"""


def _render_quality_histogram(scores: list[float]) -> str:
    if not scores:
        return ""
    # 分桶：0-0.2, 0.2-0.4, 0.4-0.6, 0.6-0.8, 0.8-1.0
    bins = [0, 0, 0, 0, 0]
    for s in scores:
        idx = min(int(s * 5), 4)
        bins[idx] += 1

    max_count = max(bins) or 1
    w, h = 400, 180
    bar_w = 60
    labels = ["0-0.2", "0.2-0.4", "0.4-0.6", "0.6-0.8", "0.8-1.0"]
    colors = ["#d25d5a", "#d4b45b", "#5178c6", "#509863", "#509863"]

    bars = ""
    for i, (count, label, color) in enumerate(zip(bins, labels, colors, strict=True)):
        bar_h = (count / max_count) * (h - 50)
        x = 30 + i * (bar_w + 12)
        y = h - 30 - bar_h
        bars += f'<rect x="{x}" y="{y}" width="{bar_w}" height="{bar_h}" fill="{color}" rx="4"/>'
        bars += f'<text x="{x + bar_w / 2}" y="{y - 5}" text-anchor="middle" font-size="12" fill="#333">{count}</text>'
        bars += f'<text x="{x + bar_w / 2}" y="{h - 10}" text-anchor="middle" font-size="11" fill="#999">{label}</text>'

    return f"""<div class="section">
<h2>质量分数分布</h2>
<div class="chart-container">
<svg width="{w}" height="{h}" viewBox="0 0 {w} {h}">{bars}</svg>
</div>
</div>"""
